// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbombgssedxfoymsltmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indib21iZ3NzZWR4Zm95bXNsdG1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NjIwNzIsImV4cCI6MjA2MTEzODA3Mn0.AuJzAjcJRFbyXbHUHKkDI9Fb2MPqQE0TOuOFTJSiGd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);